Repository DguFarmSystem/FarmSystem-FE, pull requests merged in 2025-04, with the labels that each got.

#226 fix: Google 로그인 URL 변경
  packages/auth/hooks/useSocialLogin.tsx
Labels: 🐞 BugFix, 🍇수빈

#225 feat: 파밍로그 마이페이지 프로필 사진 변경 기능 구현
  apps/farminglog/src/pages/myPage/AppView/AppView.tsx
  apps/farminglog/src/pages/myPage/WebView/WebView.tsx
  apps/farminglog/src/services/mutation/usePresignedUrlMutation.ts
Labels: ✨ Feature, 📬 API, 주형

#231 fix: 팜 홈페이지 버튼에 파밍로그 유도 + 공통 콘텐츠 레이아웃 제작
  apps/farminglog/src/layouts/WhiteContentContainer.styled.ts
  apps/farminglog/src/layouts/WhiteContentContainer.tsx
  apps/farminglog/src/pages/cheer/index.tsx
  apps/farminglog/src/pages/cheer/write/cheer.tsx
  apps/farminglog/src/pages/cheer/write/index.tsx
  apps/farminglog/src/pages/cheer/write/search.tsx
  apps/farminglog/src/pages/farminglog/create/index.tsx
  apps/farminglog/src/pages/farminglog/view/index.tsx
  apps/farminglog/src/pages/myPage/WebView/WebView.tsx
  apps/farminglog/src/pages/ranking/index.tsx
  apps/website/src/components/Header/Header.tsx
Labels: ✨ Feature, ⚙ Setting, 윤석, 🧰 Chore

#239 fix: 2차 QA 사항 반영
  apps/farminglog/src/assets/Icons/tabler_crown.png
  apps/farminglog/src/components/Header/Header.styled.ts
  apps/farminglog/src/components/Header/Header.tsx
  apps/farminglog/src/components/Popup/MessagePopup.styled.ts
  apps/farminglog/src/components/Popup/MessagePopup.tsx
  apps/farminglog/src/components/Popup/popup.styled.ts
  apps/farminglog/src/components/Popup/popup.tsx
  apps/farminglog/src/components/Popup/popup.types.ts
  apps/farminglog/src/pages/cheer/write/cheer.tsx
  apps/farminglog/src/pages/farminglog/create/index.tsx
  apps/farminglog/src/pages/home/Harvest/harvest.tsx
Labels: ✨ Feature, 💄 Stlye, 🐞 BugFix, 동민

#241 feat & fix: 에러페이지 제작 및 랭킹 페이지 QA
  apps/farminglog/src/assets/Icons/Arrow_right.png
  apps/farminglog/src/pages/error/index.styled.ts
  apps/farminglog/src/pages/error/index.tsx
  apps/farminglog/src/pages/home/Ranking/ranking.styled.ts
  apps/farminglog/src/pages/home/Ranking/ranking.tsx
  apps/farminglog/src/pages/myPage/WebView/WebView.styles.tsx
  apps/farminglog/src/pages/myPage/WebView/WebView.tsx
  apps/farminglog/src/pages/ranking/index.styles.tsx
  apps/farminglog/src/pages/ranking/index.tsx
  apps/farminglog/src/router/index.tsx
Labels: ✨ Feature, 💄 Stlye, 🐞 BugFix, 주형

#243 Fix/#242
  apps/farminglog/src/pages/cheer/index.styled.ts
  apps/farminglog/src/pages/farminglog/create/index.tsx
  apps/farminglog/src/pages/farminglog/view/Card.tsx
  apps/farminglog/src/pages/farminglog/view/index.styled.ts
  apps/farminglog/src/utils/convertUrlsToLinks.tsx
Labels: ✨ Feature, 💄 Stlye, 윤석

#256 fix: 파밍로그 페이지 트러블 슈팅 찐찐막
  apps/farminglog/src/pages/farminglog/create/index.tsx
  apps/farminglog/src/pages/farminglog/view/Card.styled.ts
  apps/farminglog/src/pages/farminglog/view/CardSkeleton.styled.ts
  apps/farminglog/src/pages/farminglog/view/CardSkeleton.tsx
  apps/farminglog/src/pages/farminglog/view/index.styled.ts
  apps/farminglog/src/pages/farminglog/view/index.tsx
Labels: ✨ Feature, 💄 Stlye, 🐞 BugFix, 윤석

#257 fix: 파밍로그 홈 화면 등 트러블 슈팅 마지막 PR
  apps/farminglog/src/assets/Icons/goodgood.png
  apps/farminglog/src/components/Header/Header.tsx
  apps/farminglog/src/components/Popup/ProfilePopup.tsx
  apps/farminglog/src/components/Popup/popup.styled.ts
  apps/farminglog/src/components/Popup/popup.tsx
  apps/farminglog/src/components/Popup/profilePopup.styled.ts
  apps/farminglog/src/pages/home/Harvest/harvest.styled.ts
  apps/farminglog/src/pages/home/Harvest/harvest.tsx
  apps/farminglog/src/pages/home/Ranking/ranking.tsx
  apps/farminglog/src/pages/ranking/components/CheerBalloon.tsx
  apps/farminglog/src/pages/ranking/index.tsx
  apps/farminglog/src/services/query/useUserRankingQuery.ts
Labels: 동민

#260 fix: 마이페이지 웹뷰, 앱뷰 트랙명, 사용자 역할 한글명으로 표시 변경
  apps/farminglog/src/pages/myPage/AppView/AppView.styles.tsx
  apps/farminglog/src/pages/myPage/AppView/AppView.tsx
  apps/farminglog/src/pages/myPage/WebView/WebView.tsx
  apps/farminglog/src/utils/convertRoleToString.ts
Labels: 🐞 BugFix, 주형

#266 hotfix: 파밍로그 링크 깨짐 수정 + 엔터키 요청 고치기 #265
  apps/farminglog/src/pages/cheer/write/cheer.tsx
  apps/farminglog/src/pages/farminglog/create/index.tsx
  apps/farminglog/src/utils/convertUrlsToLinks.tsx
Labels: 🐞 BugFix, 📬 API, 윤석

#267 hotfix: [ 배포 ] 파밍로그 링크 깨짐 수정 + 엔터키 요청 고치기
  apps/farminglog/src/pages/cheer/write/cheer.tsx
  apps/farminglog/src/pages/farminglog/create/index.tsx
  apps/farminglog/src/utils/convertUrlsToLinks.tsx
Labels: 🐞 BugFix, 윤석, 📦 Release
