Repository DguFarmSystem/FarmSystem-FE, pull requests merged in 2025-02, with the labels that each got.

#9 Feature/8 create union section
  package-lock.json
  package.json
  src/hooks/.gitkeep
  src/hooks/useMediaQueries.ts
  src/pages/Main/Union/ContentBox.styled.ts
  src/pages/Main/Union/ContentBox.tsx
  src/pages/Main/Union/Union.styled.ts
  src/pages/Main/Union/Union.tsx
Labels: ✨ Feature, 윤석

#17 feat: 트랙 및 커리큘럼 소개 섹션 제작
  .gitattributes
  src/assets/Icons/OrangeArrow.svg
  src/assets/Icons/robotarm.png
  src/assets/Images/Professors/KimDW.png
  src/assets/Images/Professors/LimSS.png
  src/assets/Images/Professors/SeokMK.png
  src/assets/Images/Professors/SongSH.png
  src/assets/Images/Professors/SunSK.png
  src/assets/Images/Professors/index.ts
  src/pages/Main/Tracks/InfoBox.styled.ts
  src/pages/Main/Tracks/InfoBox.tsx
  src/pages/Main/Tracks/Tracks.styled.ts
  src/pages/Main/Tracks/Tracks.tsx
  src/pages/Main/Tracks/TracksData.ts
Labels: ✨ Feature, 💄 Stlye, 윤석

#30 Feature/change mobile navbar
  package-lock.json
  package.json
  src/pages/Main/FarmSyetemNav/FarmSystemNav.styled.ts
  src/pages/Main/FarmSyetemNav/FarmSystemNav.tsx
  src/pages/Main/FarmSyetemNav/MobileNav.styled.ts
  src/pages/Main/FarmSyetemNav/MobileNav.tsx
Labels: ✨ Feature, 💄 Stlye, 윤석

#28 Fix/23 responsive mainpage
  src/assets/Icons/mail.png
  src/assets/Icons/robotarm.png
  src/assets/react.svg
  src/pages/Main/Tracks/InfoBox.styled.ts
  src/pages/Main/Tracks/InfoBox.tsx
  src/pages/Main/Tracks/TracksData.ts
Labels: 💄 Stlye, 🍇수빈

#29 Feature/#27
  package-lock.json
  package.json
  src/assets/Icons/FarmLogo1.png
  src/assets/Icons/IntroLogo.svg
  src/hooks/useMediaQueries.ts
  src/pages/Main/Intro/Intro.styled.tsx
  src/pages/Main/Intro/Intro.tsx
Labels: ✨ Feature, 💄 Stlye, 주형

#31 Fix/25 fix header and union section
  package-lock.json
  package.json
  src/pages/Main/FarmSyetemNav/FarmSystemNav.styled.ts
  src/pages/Main/FarmSyetemNav/FarmSystemNav.tsx
  src/pages/Main/FarmSyetemNav/MobileNav.styled.ts
  src/pages/Main/FarmSyetemNav/MobileNav.tsx
  src/pages/Main/Union/ContentBox.styled.ts
  src/pages/Main/Union/ContentBox.tsx
  src/pages/Main/Union/Union.styled.ts
Labels: ✨ Feature, ⚙ Setting, 💄 Stlye, 동민, 윤석

#42 Fix/39 tracks and union detail
  src/pages/Main/Tracks/InfoBox.styled.ts
  src/pages/Main/Tracks/Tracks.styled.ts
  src/pages/Main/Tracks/Tracks.tsx
  src/pages/Main/Union/ContentBox.styled.ts
Labels: 💄 Stlye, 윤석

#45 [Feat] 메인페이지 인트로 기존 버전으로 수정
  src/assets/Icons/IntroLogo.svg
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/pages/Main/Intro/Intro.styled.tsx
  src/pages/Main/Intro/Intro.tsx
Labels: ✨ Feature, 💄 Stlye, 주형

#65 Feat/#64 FAQ 반응형 수정
  src/pages/FAQ/Frame.styled.ts
  src/pages/FAQ/Frame.tsx
  src/pages/FAQ/Question.styled.ts
  src/pages/FAQ/Question.tsx
  src/pages/FAQ/index.styled.ts
  src/pages/FAQ/index.tsx
Labels: ✨ Feature, 💄 Stlye, 주형

#84 feat: 오픈 전 Coming soon 페이지 단순 디자인 완료
  .github/workflows/deploy.yml
  src/assets/Images/Buttons/ArrowLeft.svg
  src/assets/Images/Buttons/ArrowLeftMobile.svg
  src/assets/Images/Buttons/ArrowRight.svg
  src/assets/Images/Buttons/ArrowRightMobile.svg
  src/components/Header/Header.tsx
  src/pages/Apply/index.tsx
  src/pages/Blog/BlogList.styles.tsx
  src/pages/Blog/BlogList.tsx
  src/pages/Blog/ProjectList.styles.tsx
  src/pages/Blog/index.styles.tsx
  src/pages/FAQ/Question.styled.ts
  src/pages/Main/Achievements/Achievements.styles.ts
  src/pages/Main/Achievements/Achievements.tsx
  src/pages/Main/Intro/Intro.tsx
  src/pages/Main/Tracks/InfoBox.styled.ts
  src/pages/Main/Tracks/InfoBox.tsx
  src/pages/Main/Tracks/TracksData.ts
  src/pages/Main/index.tsx
  src/pages/MaintainPage/MaintainPage.styled.ts
  src/pages/MaintainPage/MaintainPage.tsx
Labels: ✨ Feature, 💄 Stlye, 동민

#88 fix: FAQ 페이지 폰트 적용 문제 수정
  src/pages/FAQ/Question.styled.ts
  src/pages/FAQ/index.styled.ts
  src/pages/Main/BottomInfo/BottomInfo.styles.ts
Labels: 🐞 BugFix, 윤석

#102 feat: SEO를 위해 메타데이터 + sitemap 추가
  index.html
  public/sitemap.xml
Labels: ✨ Feature, ⚙ Setting, 윤석

#105 feat: 소식 페이지 생성 및 등록된 글이 없을 때 안내 메시지 추가
  src/Router.tsx
  src/components/Header/Header.tsx
  src/pages/News/News.styles.ts
  src/pages/News/index.tsx
Labels: ✨ Feature, 🍇수빈

#113 Fix: QA 사항 반영
  .gitignore
  src/assets/DGU.png
  src/assets/Github_white.png
  src/assets/Linktree_white.png
  src/assets/instagram_white.png
  src/components/Footer/Footer.tsx
  src/pages/FAQ/Question.styled.ts
  src/pages/Main/Tracks/InfoBox.styled.ts
  src/pages/Main/Tracks/TracksData.ts
  src/pages/Main/Union/ContentBox.styled.ts
  src/pages/Main/Union/ContentBox.tsx
  src/pages/News/News.styles.ts
  src/pages/News/index.tsx
Labels: 💄 Stlye, 🐞 BugFix, 🍇수빈
