Repository DguFarmSystem/FarmSystem-FE, pull requests merged in 2025-03, with the labels that each got.

#119 feat: 메인페이지 반응형 및 스타일 최종 수정
  package-lock.json
  package.json
  src/assets/Images/Professors/HanKY.png
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/pages/Main/Achievements/AchievementItem.styles.ts
  src/pages/Main/Achievements/AchievementItem.tsx
  src/pages/Main/BottomInfo/BottomInfo.tsx
  src/pages/Main/FarmIntroduce/FarmIntroduce.styles.ts
  src/pages/Main/FarmIntroduce/FarmIntroduce.tsx
  src/pages/Main/Intro/Intro.styled.tsx
  src/pages/Main/Tracks/InfoBox.styled.ts
  src/pages/Main/Tracks/InfoBox.tsx
  src/pages/Main/Tracks/TracksData.ts
  src/pages/Main/Union/Union.styled.ts
  src/pages/Main/index.styled.tsx
  src/pages/Main/index.tsx
Labels: 🐞 BugFix, 주형

#120 feat: 메인페이지 최종 수정 버전 main에 반영
  package-lock.json
  package.json
  src/assets/Images/Professors/HanKY.png
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/pages/Main/Achievements/AchievementItem.styles.ts
  src/pages/Main/Achievements/AchievementItem.tsx
  src/pages/Main/BottomInfo/BottomInfo.tsx
  src/pages/Main/FarmIntroduce/FarmIntroduce.styles.ts
  src/pages/Main/FarmIntroduce/FarmIntroduce.tsx
  src/pages/Main/Intro/Intro.styled.tsx
  src/pages/Main/Tracks/InfoBox.styled.ts
  src/pages/Main/Tracks/InfoBox.tsx
  src/pages/Main/Tracks/TracksData.ts
  src/pages/Main/Union/Union.styled.ts
  src/pages/Main/index.styled.tsx
  src/pages/Main/index.tsx
Labels: 주형

#109 feat: 지원하기 페이지 디자인 없이 API 연결 및 관련 기능 구현 + 간단한 동작 화면
  .env.example
  package-lock.json
  package.json
  src/config/apiConfig.ts
  src/hooks/useApply.ts
  src/models/.gitkeep
  src/models/apply.ts
  src/pages/Apply/ApplyBox.tsx
  src/pages/Apply/ApplyLogin.tsx
  src/pages/Apply/ChoiceSelector.tsx
  src/pages/Apply/PersonalInfo.tsx
  src/pages/Apply/index.tsx
  src/services/.gitkeep
  src/services/apply.ts
  src/utils/.gitkeep
  src/utils/apply.ts
  src/validations/apply.ts
Labels: ✨ Feature, 📬 API, 윤석

#123 fix: apiConfig에서 env 없는 예외 처리 + api통신에서 enum 수정
  src/config/apiConfig.ts
  src/models/apply.ts
  src/pages/Apply/ApplyBox.tsx
Labels: 🐞 BugFix, 윤석

#122 feat: index.html <head>태그에 추가
  index.html
Labels: ✨ Feature, 동민

#125 feat/#108 지원하기 페이지 퍼블리싱
  src/assets/FarmLogo_Black.png
  src/assets/LeftArrow.png
  src/assets/RightArrow.png
  src/components/Header/Header.tsx
  src/pages/Apply/Application/AITrack.tsx
  src/pages/Apply/Application/Application.styles.ts
  src/pages/Apply/Application/Application.tsx
  src/pages/Apply/Application/BigDataTrack.tsx
  src/pages/Apply/Application/GameTrack.tsx
  src/pages/Apply/Application/IoTTrack.tsx
  src/pages/Apply/Application/SecureWebTrack.tsx
  src/pages/Apply/Application/questionsData.ts
  src/pages/Apply/Step1/Step1.styles.ts
  src/pages/Apply/Step1/Step1.tsx
  src/pages/Apply/Step2/Step2.styles.ts
  src/pages/Apply/Step2/Step2.tsx
  src/pages/Apply/index.tsx
  src/pages/Layout.tsx
  src/pages/Main/Intro/Intro.tsx
Labels: ✨ Feature, 💄 Stlye, 주형

#124 fix: 지원하기 URL recruit으로 변경 + 에러 헨들링 강화
  package-lock.json
  package.json
  src/Router.tsx
  src/components/Header/Header.tsx
  src/hooks/useApply.ts
  src/pages/Apply/ApplyLogin.tsx
  src/pages/Main/BottomInfo/BottomInfo.tsx
  src/pages/Main/Intro/Intro.tsx
  src/utils/handleApiError.ts
Labels: ✨ Feature, 📬 API, 윤석

#128 feat/#127 지원하기 페이지 병합 작업
  src/components/Popup/Popup.styled.tsx
  src/components/Popup/Popup.tsx
  src/pages/Apply/Application/AITrack.tsx
  src/pages/Apply/Application/Application.styles.ts
  src/pages/Apply/Application/Application.tsx
  src/pages/Apply/Application/Legacy/AITrack.tsx
  src/pages/Apply/Application/Legacy/BigDataTrack.tsx
  src/pages/Apply/Application/Legacy/GameTrack.tsx
  src/pages/Apply/Application/Legacy/IoTTrack.tsx
  src/pages/Apply/Application/Legacy/SecureWebTrack.tsx
  src/pages/Apply/Application/PersonInfo.tsx
  src/pages/Apply/Step1/Step1.styles.ts
  src/pages/Apply/Step1/Step1.tsx
  src/pages/Apply/Step2/Step2.styles.ts
  src/pages/Apply/Step2/Step2.tsx
  src/pages/Apply/index.tsx
  src/pages/Layout.tsx
Labels: ✨ Feature, 📬 API, 주형

#130 feat/#127 지원 페이지 오류 수정
  src/components/Footer/Footer.tsx
  src/pages/Apply/Application/Application.styles.ts
  src/pages/Apply/Application/Application.tsx
  src/pages/Apply/Step1/Step1.styles.ts
  src/pages/Apply/Step1/Step1.tsx
  src/pages/Apply/Step2/Step2.styles.ts
  src/pages/Apply/Step2/Step2.tsx
  src/pages/Main/BottomInfo/BottomInfo.tsx
Labels: 🐞 BugFix, 주형

#134 fix: 임시저장 클릭시 지원하기 1 step으로 이동
  package-lock.json
  package.json
  src/pages/Apply/ApplyBox.tsx
Labels: ✨ Feature, 🍇수빈

#140 deploy: 세부 수정사항 메인에 반영
  src/components/Header/Header.styled.tsx
  src/pages/Apply/Application/Application.tsx
  src/pages/Apply/Application/PersonInfo.tsx
  src/pages/Apply/ApplyBox.tsx
  src/pages/Apply/ApplyLogin.tsx
  src/pages/Apply/Step2/Step2.tsx
  src/pages/Blog/ProjectList.tsx
  src/pages/Main/BottomInfo/BottomInfo.tsx
  src/pages/Main/Intro/Intro.styled.tsx
  src/pages/Main/Intro/Intro.tsx
  src/pages/Main/Tracks/Tracks.styled.ts
  src/utils/Logger.ts
Labels: ✨ Feature, ⚙ Setting, 🌏 Deploy, 🐞 BugFix, 윤석

#145 feat: 소식 API 연결 + 퍼블리싱 데이터 받아온 부분까지만
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/Images/news/PlaceHolder.png
  src/hooks/useNews.ts
  src/models/news.ts
  src/pages/Apply/ApplyBox.tsx
  src/pages/News/News.styles.ts
  src/pages/News/NewsDetail/index.styled.ts
  src/pages/News/NewsDetail/index.tsx
  src/pages/News/NewsItem.styled.ts
  src/pages/News/NewsItem.tsx
  src/pages/News/index.styled.ts
  src/pages/News/index.tsx
  src/services/news.ts
  vite.config.ts
Labels: ✨ Feature, 💄 Stlye, 📬 API, 윤석

#150 feat: 네이버 SEO 추가 + 구글 SEO 최적화
  index.html
Labels: ✨ Feature, 동민

#152 feat: 지원 페이지 닫기
  src/Router.tsx
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/components/RedirectRoute.tsx
  src/pages/Main/BottomInfo/BottomInfo.styles.ts
  src/pages/Main/BottomInfo/BottomInfo.tsx
  src/pages/Main/Intro/Intro.styled.tsx
  src/pages/Main/Intro/Intro.tsx
Labels: ✨ Feature, 윤석

#155 chore: 모노레포 충돌 해결
  apps/website/index.html
  apps/website/src/Router.tsx
  apps/website/src/components/Header/Header.styled.tsx
  apps/website/src/components/Header/Header.tsx
  apps/website/src/components/RedirectRoute.tsx
  apps/website/src/hooks/useBlog.ts
  apps/website/src/hooks/useLinkPreview.ts
  apps/website/src/models/blog.ts
  apps/website/src/pages/Blog/Blog/BlogItem.styles.tsx
  apps/website/src/pages/Blog/Blog/BlogItem.tsx
  apps/website/src/pages/Blog/Blog/BlogList.styles.tsx
  apps/website/src/pages/Blog/Blog/BlogList.tsx
  apps/website/src/pages/Blog/BlogItem.tsx
  apps/website/src/pages/Blog/BlogList.tsx
  apps/website/src/pages/Blog/Project/ProjectItem.style.tsx
  apps/website/src/pages/Blog/Project/ProjectItem.tsx
  apps/website/src/pages/Blog/Project/ProjectList.styles.tsx
  apps/website/src/pages/Blog/Project/ProjectList.tsx
  apps/website/src/pages/Blog/ProjectItem.tsx
  apps/website/src/pages/Blog/index.styles.tsx
  apps/website/src/pages/Blog/index.tsx
  apps/website/src/pages/Main/BottomInfo/BottomInfo.styles.ts
  apps/website/src/pages/Main/BottomInfo/BottomInfo.tsx
  apps/website/src/pages/Main/Intro/Intro.styled.tsx
  apps/website/src/pages/Main/Intro/Intro.tsx
  apps/website/src/pages/News/NewsItem.tsx
  apps/website/src/pages/News/index.styled.ts
  apps/website/src/pages/News/index.tsx
  apps/website/src/services/blog.ts
  pnpm-lock.yaml
Labels: ⚙ Setting, 🐞 BugFix, 윤석

#163 fix: ci pnpm으로 변경 + 캐시 적용해보기
  .github/workflows/ci.yml
  README.md
Labels: ⚙ Setting, 🐞 BugFix, 윤석

#168 fix: 터보레포 빌드 오류 수정 + 공통 패키지 테스트
  apps/admin/package.json
  apps/farminglog/src/Router.tsx
  apps/farminglog/src/hooks/useApplications.ts
  apps/farminglog/src/hooks/useApplyList.ts
  apps/farminglog/src/hooks/useVerifyStudent.ts
  apps/website/package.json
  apps/website/src/Router.tsx
  apps/website/src/hooks/useLinkPreview.ts
  apps/website/src/services/apply.ts
  apps/website/src/services/blog.ts
  apps/website/src/services/news.ts
  packages/api/config/apiConfig.ts
  packages/api/config/interceptors.ts
  packages/api/config/vite-env.d.ts
  packages/api/models/auth.ts
  packages/api/models/user.ts
  packages/api/package.json
  packages/api/services/tokenService.ts
  packages/api/stores/authStore.ts
  packages/api/stores/userStore.ts
  packages/config/apiConfig.ts
  packages/config/package.json
  packages/config/react-library.json
  packages/config/vite.config.ts
  turbo.json
Labels: ✨ Feature, ⚙ Setting, 🐞 BugFix, 윤석

#176 feat: 파밍로그 마이페이지 퍼블리싱
  apps/farminglog/package-lock.json
  apps/farminglog/package.json
  apps/farminglog/src/assets/Icons/BackArrow.png
  apps/farminglog/src/assets/Icons/BackArrow.svg
  apps/farminglog/src/assets/Icons/Github.png
  apps/farminglog/src/assets/Icons/Github.svg
  apps/farminglog/src/assets/Icons/Notion.png
  apps/farminglog/src/assets/Icons/Notion.svg
  apps/farminglog/src/assets/Icons/PhoneIcon.png
  apps/farminglog/src/assets/Icons/Seed.png
  apps/farminglog/src/hooks/useMediaQueries.ts
  apps/farminglog/src/pages/MyPage/AppView/AppView.styles.tsx
  apps/farminglog/src/pages/MyPage/AppView/AppView.tsx
  apps/farminglog/src/pages/MyPage/WebView/WebView.styles.tsx
  apps/farminglog/src/pages/MyPage/WebView/WebView.tsx
  apps/farminglog/src/pages/MyPage/index.tsx
  package.json
  pnpm-lock.yaml
Labels: ✨ Feature, 💄 Stlye, 주형

#175 feat: 소셜 로그인 및 사용자 정보 관리 로직 구현
  apps/farminglog/package.json
  apps/farminglog/src/App.tsx
  apps/farminglog/src/index.css
  apps/farminglog/src/pages/Auth/index.tsx
  apps/farminglog/src/pages/Auth/styles.ts
  apps/farminglog/src/pages/Auth/styles/styles.ts
  apps/farminglog/src/pages/callback.tsx
  apps/farminglog/src/router/AppRouter.tsx
  apps/farminglog/src/router/index.tsx
  apps/farminglog/src/services/mutation/example.ts
  apps/farminglog/src/services/query/exampleNoToken.ts
  apps/farminglog/src/services/query/exampleToken.ts
  apps/farminglog/src/services/queryKeys.ts
  apps/farminglog/tsconfig.app.json
  packages/api/config/apiConfig.ts
  packages/api/config/interceptors.ts
  packages/api/hooks/usePrivateApi.ts
  packages/api/hooks/usePublicApi.ts
  packages/api/models/api.ts
  packages/api/models/auth.ts
  packages/api/services/mutation/useReissueAccessTokenMutation.ts
  packages/api/services/tokenService.ts
  packages/api/stores/userStore.ts
  packages/api/utils/getClientSideTokens.ts
  packages/auth/hooks/useSocialLogin.tsx
  packages/auth/models/auth.ts
  packages/auth/models/kakao.d.ts
  packages/auth/models/social.ts
  packages/auth/models/user.ts
  packages/auth/package.json
  packages/auth/services/mutation/useSocialLoginPostMutation.ts
  packages/auth/services/mutation/useUpdateUserMutation.ts
  packages/auth/services/query/useUserInfoQuery.ts
  packages/auth/services/queryKeys.ts
  packages/auth/stores/authStore.ts
  packages/auth/stores/userStore.ts
  packages/config/vite-env.d.ts
  packages/router/protectedLoader.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 🍇수빈

#179 feat: 파밍로그 랭킹페이지 퍼블리싱
  apps/farminglog/src/assets/Icons/FarmSystem_Logo.png
  apps/farminglog/src/assets/Icons/crown.png
  apps/farminglog/src/assets/Images/Balloon.png
  apps/farminglog/src/assets/Images/RankingPhrase.png
  apps/farminglog/src/assets/Images/RankingPhrase_App.png
  apps/farminglog/src/pages/Ranking/index.styles.tsx
  apps/farminglog/src/pages/Ranking/index.tsx
Labels: ✨ Feature, 💄 Stlye, 주형

#182 feat: 파밍로그 페이지 퍼블리싱
  apps/docs/.gitignore
  apps/farminglog/src/assets/Icons/Polygon-1.png
  apps/farminglog/src/assets/Icons/chevron-right.png
  apps/farminglog/src/assets/Icons/corner-up-left.png
  apps/farminglog/src/assets/Icons/edit-3.png
  apps/farminglog/src/assets/Icons/file-plus.png
  apps/farminglog/src/assets/Icons/heart-fill.png
  apps/farminglog/src/assets/Icons/heart.png
  apps/farminglog/src/assets/Icons/polygon-1.png
  apps/farminglog/src/assets/Icons/x.png
  apps/farminglog/src/assets/icons/Polygon-1.png
  apps/farminglog/src/assets/icons/chevron-right.png
  apps/farminglog/src/assets/icons/corner-up-left.png
  apps/farminglog/src/assets/icons/edit-3.png
  apps/farminglog/src/assets/icons/file-plus.png
  apps/farminglog/src/assets/icons/heart-fill.png
  apps/farminglog/src/assets/icons/heart.png
  apps/farminglog/src/assets/icons/x.png
  apps/farminglog/src/assets/images/blank-image.png
  apps/farminglog/src/pages/farminglog/creat/index.tsx
  apps/farminglog/src/pages/farminglog/create/index.styled.ts
  apps/farminglog/src/pages/farminglog/create/index.tsx
  apps/farminglog/src/pages/farminglog/view/Card.styled.ts
  apps/farminglog/src/pages/farminglog/view/Card.tsx
  apps/farminglog/src/pages/farminglog/view/index.styled.ts
  apps/farminglog/src/pages/farminglog/view/index.tsx
  package.json
  pnpm-lock.yaml
Labels: ✨ Feature, 💄 Stlye, 윤석

#183 feat: 소셜 로그인 단계별 인증 플로우 및 에러 처리 개선 + UI 반응형 작업 완료
  apps/farminglog/src/Router.tsx
  apps/farminglog/src/assets/buttons/google.login.png
  apps/farminglog/src/assets/buttons/kakao.login.png
  apps/farminglog/src/assets/buttons/kakao_login_large_wide.png
  apps/farminglog/src/assets/logos/FarmingLog FarmingLog.png
  apps/farminglog/src/assets/logos/FarmingLog.png
  apps/farminglog/src/assets/logos/logo.basic.png
  apps/farminglog/src/assets/logos/logo.kr.png
  apps/farminglog/src/hooks/useSocialLogin.tsx
  apps/farminglog/src/pages/Auth/SocialRedirect.tsx
  apps/farminglog/src/pages/Auth/components/AuthButton.tsx
  apps/farminglog/src/pages/Auth/components/StepAuthComplete.tsx
  apps/farminglog/src/pages/Auth/components/StepCheckName.tsx
  apps/farminglog/src/pages/Auth/components/StepInputStudentId.tsx
  apps/farminglog/src/pages/Auth/components/StepNotMember.tsx
  apps/farminglog/src/pages/Auth/components/StepStart.tsx
  apps/farminglog/src/pages/Auth/components/index.tsx
  apps/farminglog/src/pages/Auth/index.tsx
  apps/farminglog/src/pages/Auth/styles.ts
  apps/farminglog/src/pages/Auth/styles/StepCheckName.styled.ts
  apps/farminglog/src/pages/Auth/styles/StepInputStudentId.styled.tsx
  apps/farminglog/src/pages/Auth/styles/StepNotMember.styled.ts
  apps/farminglog/src/pages/Auth/styles/StepStartStyled.ts
  apps/farminglog/src/pages/Auth/styles/indexStyled.ts
  apps/farminglog/src/pages/Auth/styles/styles.ts
  apps/farminglog/src/pages/callback.tsx
  apps/farminglog/src/router/index.tsx
  apps/farminglog/tsconfig.app.json
  packages/api/hooks/usePublicApi.ts
  packages/api/services/mutation/useUserVerifyMutation.ts
  packages/auth/hooks/useSocialLogin.tsx
  packages/auth/services/mutation/useSocialLoginPostMutation.ts
  packages/auth/stores/authStore.ts
  packages/auth/stores/useAuthStore.ts
Labels: ✨ Feature, 💄 Stlye, 🍇수빈

#192 feat: 랭킹 페이지 말풍선 및 표지판 코드 변환
  apps/farminglog/package.json
  apps/farminglog/src/assets/Icons/good.png
  apps/farminglog/src/assets/Icons/person.png
  apps/farminglog/src/components/Header/Header.tsx
  apps/farminglog/src/components/Ranking/sign.styles.tsx
  apps/farminglog/src/components/Ranking/sign.tsx
  apps/farminglog/src/pages/Ranking/components/CheerBalloon.styles.tsx
  apps/farminglog/src/pages/Ranking/components/CheerBalloon.tsx
  apps/farminglog/src/pages/Ranking/index.tsx
  apps/farminglog/src/pages/home/Ranking/ranking.tsx
  apps/farminglog/src/pages/myPage/AppView/AppView.tsx
  apps/farminglog/src/router/index.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 💄 Stlye, 주형

#200 feat: FarmingLog 페이지 API 연결하기
  apps/farminglog/src/assets/Icons/edit-3.png
  apps/farminglog/src/assets/icons/edit-3.png
  apps/farminglog/src/models/farminglog.ts
  apps/farminglog/src/pages/farminglog/create/index.styled.ts
  apps/farminglog/src/pages/farminglog/create/index.tsx
  apps/farminglog/src/pages/farminglog/view/Card.styled.ts
  apps/farminglog/src/pages/farminglog/view/Card.tsx
  apps/farminglog/src/pages/farminglog/view/index.styled.ts
  apps/farminglog/src/pages/farminglog/view/index.tsx
  apps/farminglog/src/services/mutation/FarmingLog/index.ts
  apps/farminglog/src/services/mutation/FarmingLog/useCreateFarmingLogMutation.ts
  apps/farminglog/src/services/mutation/FarmingLog/useEditFarmingLogMutation.ts
  apps/farminglog/src/services/mutation/FarmingLog/useToggleLikeMutation.ts
  apps/farminglog/src/services/query/useFarmingLogInfiniteQuery.ts
  apps/farminglog/src/services/queryKeys.ts
  apps/farminglog/src/stores/farminglogStore.ts
  package.json
  packages/api/hooks/usePrivateApi.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 💄 Stlye, 📬 API, 윤석

#205 feat: 랭킹페이지, 마이페이지 버그 및 기능 수정
  apps/farminglog/package.json
  apps/farminglog/src/assets/buttons/ImageEdit.png
  apps/farminglog/src/pages/cheer/write/index.tsx
  apps/farminglog/src/pages/myPage/AppView/AppView.styles.tsx
  apps/farminglog/src/pages/myPage/AppView/AppView.tsx
  apps/farminglog/src/pages/myPage/WebView/WebView.styles.tsx
  apps/farminglog/src/pages/myPage/WebView/WebView.tsx
  apps/farminglog/src/pages/ranking/index.styles.tsx
  apps/farminglog/src/pages/ranking/index.tsx
  pnpm-lock.yaml
Labels: 🐞 BugFix, 주형

#206 fix : 홈페이지 홈 화면, 헤더 수정 사항 반영
  apps/farminglog/src/components/Header/Header.styled.ts
  apps/farminglog/src/components/Header/Header.tsx
  apps/farminglog/src/pages/home/Cheer/cheer.styled.ts
  apps/farminglog/src/pages/home/Cheer/cheer.tsx
  apps/farminglog/src/pages/home/Harvest/harvest.styled.ts
  apps/farminglog/src/pages/home/Harvest/harvest.tsx
  apps/farminglog/src/pages/home/Ranking/ranking.styled.ts
  apps/farminglog/src/pages/home/Ranking/ranking.tsx
  apps/farminglog/src/stores/harvestStore.ts
  apps/farminglog/src/utils/convertTagToCategory.ts
  packages/auth/stores/userStore.ts
Labels: ✨ Feature, 🐞 BugFix, 동민
